---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: kub/hasd_api_image:v7.0
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: db_name
              value: HumanActivityPredictionsDB

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 7000
    name: flask-service
    protocol: TCP
    targetPort: 7000
  selector:
    app: flaskapi
  type: LoadBalancer