FEATURES = ['AUDIO_X', 'AUDIO_Z', 'pressure', 'MAG_Z', 'MAG_X', 'MAG_Y',
            'GRAVITY_X', 'ACC_X', 'ROTATION_VECTOR_A', 'ROTATION_VECTOR_C', 'ORI_X',
            'ROTATION_VECTOR_D', 'GRAVITY_Y', 'AUDIO_W', 'GRAVITY_Z']

LABEL_DICT = {'Walk': 0,
              'At home': 1,
              'In bus': 2,
              'Eat': 3,
              'In computer': 4,
              'Train': 5,
              'In computer/At home': 6,
              'In vehicle': 7,
              'Cooking': 8,
              'Pause': 9,
              'Meeting': 10,
              'Eat/At home': 11,
              'Work': 12,
              'Movie': 13,
              'Phone was out of the pocket (forgot)/At home': 14,
              'Video games/At home': 15,
              'Shop': 16,
              'In computer/Work': 17,
              'Shop/Walk': 18,
              'Sleep': 19,
              'Picnic ': 20,
              'Walking&party': 21,
              'Eat/Phone was out of the pocket (forgot)/At home': 22,
              'On bus stop': 23,
              'On bus stop/Walk': 24,
              'Took off glasses/Shop/Walk': 25,
              'Video games': 26,
              'Shopping& wearing': 27,
              'Eat/In computer': 28}

STATUS_MESSAGE_DICT = {0:"In progress",
                       1:"Completed",
                       2:"Failed"}
