FEATURES = ['Phone_pressure', 'Phone_ACC_X', 'Phone_ACC_Y', 'Phone_ACC_Z',
       'Phone_GRAVITY_X', 'Phone_GRAVITY_Y', 'Phone_GRAVITY_Z', 'Phone_GYRO_X',
       'Phone_GYRO_Y', 'Phone_GYRO_Z', 'Phone_LA_X', 'Phone_LA_Y',
       'Phone_LA_Z', 'Phone_MAG_X', 'Phone_MAG_Y', 'Phone_MAG_Z',
       'Phone_ORI_X', 'Phone_ORI_Y', 'Phone_ORI_Z', 'Phone_AUDIO_W',
       'Phone_AUDIO_X', 'Phone_AUDIO_Y', 'Phone_AUDIO_Z',
       'Phone_ROTATION_VECTOR_A', 'Phone_ROTATION_VECTOR_B',
       'Phone_ROTATION_VECTOR_C', 'Phone_ROTATION_VECTOR_D',
       'Phone_ROTATION_VECTOR_E']

LABEL_DICT = {'Walk': 0,
              'At home': 1,
              'In bus': 2,
              'Eat': 3,
              'In computer': 4,
              'Train': 5,
              'In computer/At home': 6,
              'In vehicle': 7,
              'Cooking': 8,
              'Pause': 9,
              'Meeting': 10,
              'Eat/At home': 11,
              'Work': 12,
              'Movie': 13,
              'Phone was out of the pocket (forgot)/At home': 14,
              'Video games/At home': 15,
              'Shop': 16,
              'In computer/Work': 17,
              'Shop/Walk': 18,
              'Sleep': 19,
              'Picnic ': 20,
              'Walking&party': 21,
              'Eat/Phone was out of the pocket (forgot)/At home': 22,
              'On bus stop': 23,
              'On bus stop/Walk': 24,
              'Took off glasses/Shop/Walk': 25,
              'Video games': 26,
              'Shopping& wearing': 27,
              'Eat/In computer': 28}

STATUS_MESSAGE_DICT = {0:"In progress",
                       1:"Completed",
                       2:"Failed"}
